services:
  db-mysql-sso:
    image: mysql:5.7.40
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD  -e 'SHOW databases'"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_PORT}:3306"
    expose:
      - 3306
    volumes:
      - mysql-data-sso:/var/lib/mysql
    networks:
      - sso-network
  backend:
    image: ${DOCKER_USERNAME_SSO}/sso-backend-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db-mysql-sso
    environment:
      - DB_PORT=3306
      - DB_HOST=db-mysql-sso
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./src:/sso-api/backend/src
      - ./package.json:/sso-api/backend/package.json
    networks:
      - sso-network
volumes:
  mysql-data-sso:

networks:
  sso-network:
    driver: bridge
#docker compose up -d --build

#docker exec -i db-mysql-sso mysql -uroot -p${DB_PASSWORD} --default-character-set=utf8mb4 ${DB_NAME} < init.sql
